# Generated by Django 5.2.5 on 2025-08-26 02:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_status'),
        ('job', '0002_job_create_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationslughistory',
            name='update_at',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'jobseeker')},
        ),
    ]
