# Generated by Django 5.2.5 on 2025-08-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewer',
            new_name='jobseeker',
        ),
    ]
